/* cardapio.js — Cardápio Demonstrativo RibbsZn (novo) */
/* Baseado nas imagens enviadas — apenas exibição, sem pedidos */

window.CATEGORIES = [
  "Destilados",
  "Petiscos / Porções",
  "Espetinhos",
  "Drinks",
  "Sucos e Refrigerantes",
  "Cervejas",
];

window.CARDAPIO = [
  /* DESTILADOS */
  {
    id: "gordon_litro",
    name: "Gordon’s Litro",
    price: 99.99,
    category: "Destilados",
    image: "imgs/gordons.jpg",
  },
  {
    id: "gordon_dose",
    name: "Gordon’s Dose",
    price: 7.99,
    category: "Destilados",
    image: "imgs/gordons.jpg",
  },
  {
    id: "tanqueray_litro",
    name: "Tanqueray Litro",
    price: 159.0,
    category: "Destilados",
    image: "imgs/tanqueray.webp",
  },
  {
    id: "tanqueray_dose",
    name: "Tanqueray Dose",
    price: 9.99,
    category: "Destilados",
    image: "imgs/tanqueray.webp",
  },
  {
    id: "oldpar_litro",
    name: "Old Parr Litro",
    price: 169.0,
    category: "Destilados",
    image: "imgs/oldparr.png",
  },
  {
    id: "oldpar_dose",
    name: "Old Parr Dose",
    price: 10.99,
    category: "Destilados",
    image: "imgs/oldparr.png",
  },
  {
    id: "blackwhite_litro",
    name: "Black & White Litro",
    price: 89.0,
    category: "Destilados",
    image: "imgs/blackwhite.jpg",
  },
  {
    id: "blackwhite_dose",
    name: "Black & White Dose",
    price: 6.9,
    category: "Destilados",
    image: "imgs/blackwhite.jpg",
  },
  {
    id: "redlabel_litro",
    name: "Red Label Litro",
    price: 119.99,
    category: "Destilados",
    image: "imgs/redlabel.jpg",
  },
  {
    id: "redlabel_dose",
    name: "Red Label Dose",
    price: 7.49,
    category: "Destilados",
    image: "imgs/redlabel.jpg",
  },
  {
    id: "smirnoff_litro",
    name: "Smirnoff Litro",
    price: 64.99,
    category: "Destilados",
    image: "imgs/smirnoff.jpg",
  },
  {
    id: "smirnoff_dose",
    name: "Smirnoff Dose",
    price: 5.9,
    category: "Destilados",
    image: "imgs/smirnoff.jpg",
  },
  {
    id: "campari_litro",
    name: "Campari Litro",
    price: 89.99,
    category: "Destilados",
    image: "imgs/campari.png",
  },
  {
    id: "campari_dose",
    name: "Campari Dose",
    price: 6.9,
    category: "Destilados",
    image: "imgs/campari.png",
  },
  {
    id: "bananinha_litro",
    name: "Bananinha Litro",
    price: 84.99,
    category: "Destilados",
    image: "imgs/bananinha.webp",
  },
  {
    id: "bananinha_dose",
    name: "Bananinha Dose",
    price: 5.99,
    category: "Destilados",
    image: "imgs/bananinha.webp",
  },
  {
    id: "pitu_garrafa",
    name: "Pitú Garrafinha",
    price: 9.99,
    category: "Destilados",
    image: "imgs/pitu.webp",
  },
  {
    id: "matuta_garrafa",
    name: "Matuta Garrafinha",
    price: 14.99,
    category: "Destilados",
    image: "imgs/matuta.jpg",
  },
  {
    id: "bacardi_dose",
    name: "Bacardi Dose",
    price: 5.9,
    category: "Destilados",
    image: "imgs/bacardi.webp",
  },

  /* PETISCOS */
  {
    id: "picanha_esquina",
    name: "Picanha do Eskina",
    price: 79.9,
    category: "Petiscos / Porções",
    description:
      "Picanha, macaxeira temperada e batata frita com queijo coalho.",
    image: "imgs/picanhadoeskina.jpg",
  },
  {
    id: "carne_sol_cremosa",
    name: "Carne de Sol Cremosa",
    price: 48.99,
    category: "Petiscos / Porções",
    description: "Com creme gorgonzola, fritas e pão da casa.",
    image: "imgs/carnedesolcremosa.jpg",
  },
  {
    id: "carne_sol_fritas",
    name: "Carne de Sol Acebolada c/ Fritas",
    price: 35.99,
    category: "Petiscos / Porções",
    image: "imgs/carnedesolfritas.jpg",
  },
  {
    id: "asinha_coxinha",
    name: "Asinha e Coxinha c/ Fritas",
    price: 33.99,
    category: "Petiscos / Porções",
    image: "imgs/asinhafritas.jpg",
  },
  {
    id: "camarao_alho",
    name: "Camarão ao Alho e Óleo",
    price: 33.99,
    category: "Petiscos / Porções",
    image: "imgs/camarao.jpg",
  },
  {
    id: "camarao_crocante",
    name: "Camarão Crocante",
    price: 44.99,
    category: "Petiscos / Porções",
    image: "imgs/camaraocrocante.jpg",
  },
  {
    id: "croquete_charque",
    name: "Croquete de Charque",
    price: 23.99,
    category: "Petiscos / Porções",
    image: "imgs/croquete_charque.jpg",
  },
  {
    id: "croquete_costela",
    name: "Croquete de Costela",
    price: 23.99,
    category: "Petiscos / Porções",
    image: "imgs/croquete_costela.jpg",
  },
  {
    id: "croquete_reino",
    name: "Croquete de Queijo do Reino",
    price: 25.99,
    category: "Petiscos / Porções",
    image: "imgs/croquete_charque.jpg",
  },
  {
    id: "croquete_bacalhau",
    name: "Croquete de Bacalhau",
    price: 25.99,
    category: "Petiscos / Porções",
    image: "imgs/croquete_charque.jpg",
  },
  {
    id: "pastel_nordestino",
    name: "Pastel Nordestino",
    price: 17.99,
    category: "Petiscos / Porções",
    image: "imgs/pastel.jpg",
  },
  {
    id: "batata_tradicional",
    name: "Batata Frita Tradicional",
    price: 17.99,
    category: "Petiscos / Porções",
    image: "imgs/batata.jpg",
  },
  {
    id: "batata_costela",
    name: "Batata c/ Costela",
    price: 27.99,
    category: "Petiscos / Porções",
    image: "imgs/batata_costela.jpg",
  },
  {
    id: "calabresa_fritas",
    name: "Calabresa c/ Fritas",
    price: 25.99,
    category: "Petiscos / Porções",
    image: "imgs/calabresafritas.jpg",
  },
  {
    id: "tripinha",
    name: "Tripinha Suína",
    price: 21.99,
    category: "Petiscos / Porções",
    image: "imgs/tripinha.jpg",
  },
  {
    id: "panceta",
    name: "Panceta",
    price: 17.99,
    category: "Petiscos / Porções",
    image: "imgs/panceta.jpg",
  },
  {
    id: "torresmo",
    name: "Torresmo Super Crocante",
    price: 25.99,
    category: "Petiscos / Porções",
    image: "imgs/torresmo.webp",
  },
  {
    id: "peixe_fritas",
    name: "Posta de Peixe (Atum) c/ Fritas",
    price: 54.99,
    category: "Petiscos / Porções",
    image: "imgs/peixe.jpg",
  },

  /* ESPETINHOS */
  {
    id: "salsichao",
    name: "Salsichão",
    price: 6.0,
    category: "Espetinhos",
    image: "imgs/salsichao.jpg",
  },
  {
    id: "pao_alho",
    name: "Pão de Alho",
    price: 6.0,
    category: "Espetinhos",
    image: "imgs/pao_alho.jpg",
  },
  {
    id: "carne",
    name: "Carne",
    price: 10.0,
    category: "Espetinhos",
    image: "imgs/espetinho.jpg",
  },
  {
    id: "carne_queijo",
    name: "Carne c/ Queijo",
    price: 12.0,
    category: "Espetinhos",
    image: "imgs/espetinho.jpg",
  },
  {
    id: "carne_bacon",
    name: "Carne c/ Bacon",
    price: 12.0,
    category: "Espetinhos",
    image: "imgs/espetinho.jpg",
  },
  {
    id: "frango",
    name: "Frango",
    price: 10.0,
    category: "Espetinhos",
    image: "imgs/frango.jpg",
  },
  {
    id: "frango_queijo",
    name: "Frango c/ Queijo",
    price: 12.0,
    category: "Espetinhos",
    image: "imgs/frangoqueijo.jpg",
  },
  {
    id: "frango_bacon",
    name: "Frango c/ Bacon",
    price: 12.0,
    category: "Espetinhos",
    image: "imgs/frango_bacon.jpg",
  },
  {
    id: "coracao",
    name: "Coração",
    price: 8.0,
    category: "Espetinhos",
    image: "imgs/coracao.jpg",
  },

  /* DRINKS */
  {
    id: "caipirinha",
    name: "Caipirinha",
    price: 9.99,
    category: "Drinks",
    image: "imgs/caipirinha.webp",
  },
  {
    id: "caipirinha_frutas",
    name: "Caipirinha c/ Frutas",
    price: 11.99,
    category: "Drinks",
    image: "imgs/caipirinha_frutas.png",
  },
  {
    id: "caipiroska",
    name: "Caipiroska",
    price: 13.9,
    category: "Drinks",
    image: "imgs/caipiroska.jpg",
  },
  {
    id: "caipifrutas",
    name: "Caipifrutas (Vodka)",
    price: 14.9,
    category: "Drinks",
    image: "imgs/caipirinha_frutas.png",
  },
  {
    id: "gin_tropical",
    name: "Gin Tropical",
    price: 18.9,
    category: "Drinks",
    image: "imgs/gin_tropical.jpg",
  },
  {
    id: "gin_frutas",
    name: "Gin c/ Frutas",
    price: 18.9,
    category: "Drinks",
    image: "imgs/gin_tropical.jpg",
  },
  {
    id: "daiquiri",
    name: "Daiquiri Frozen",
    price: 18.9,
    category: "Drinks",
    image: "imgs/daiquiri.jpg",
  },
  {
    id: "sex_beach",
    name: "Sex on the Beach",
    price: 18.9,
    category: "Drinks",
    image: "imgs/sex_on.jpg",
  },
  {
    id: "blue_lagoon",
    name: "Blue Lagoon",
    price: 18.9,
    category: "Drinks",
    image: "imgs/blue_lagoon.jpg",
  },
  {
    id: "cuba_libre",
    name: "Cuba Libre",
    price: 18.9,
    category: "Drinks",
    image: "imgs/cuba_libre.jpg",
  },
  {
    id: "soda_italiana",
    name: "Soda Italiana",
    price: 17.9,
    category: "Drinks",
    image: "imgs/soda_italiana.jpg",
  },

  /* SUCOS / REFRIGERANTES */
  {
    id: "limonada_copo",
    name: "Limonada (Copo)",
    price: 8.99,
    category: "Sucos e Refrigerantes",
    image: "imgs/limonada_copo.jpg",
  },
  {
    id: "limonada_jarra",
    name: "Limonada (Jarra)",
    price: 16.99,
    category: "Sucos e Refrigerantes",
    image: "imgs/limonada_jarra.webp",
  },
  {
    id: "laranja_copo",
    name: "Suco de Laranja (Copo)",
    price: 8.99,
    category: "Sucos e Refrigerantes",
    image: "imgs/laranja_copo.jpg",
  },
  {
    id: "laranja_jarra",
    name: "Suco de Laranja (Jarra)",
    price: 16.99,
    category: "Sucos e Refrigerantes",
    image: "imgs/laranja_jarra.webp",
  },
  {
    id: "agua",
    name: "Água Mineral",
    price: 5.0,
    category: "Sucos e Refrigerantes",
    image: "imgs/agua_mineral.webp",
  },
  {
    id: "tonica",
    name: "Água Tônica",
    price: 5.99,
    category: "Sucos e Refrigerantes",
    image: "imgs/tonica.jpg",
  },
  {
    id: "coca",
    name: "Coca-Cola KS",
    price: 7.25,
    category: "Sucos e Refrigerantes",
    image: "imgs/coca_ks.webp",
  },

  /* CERVEJAS */
  {
    id: "heineken",
    name: "Heineken 600ml",
    price: 12.99,
    category: "Cervejas",
    image: "imgs/heineken600.webp",
  },
  {
    id: "stella",
    name: "Stella 600ml",
    price: 12.99,
    category: "Cervejas",
    image: "imgs/stella.jpg",
  },
  {
    id: "budweiser",
    name: "Budweiser 600ml",
    price: 12.99,
    category: "Cervejas",
    image: "imgs/budweiser.webp",
  },
  {
    id: "amstel",
    name: "Amstel 600ml",
    price: 10.99,
    category: "Cervejas",
    image: "imgs/amstel.png",
  },
  {
    id: "eisenbahn",
    name: "Eisenbahn 600ml",
    price: 10.99,
    category: "Cervejas",
    image: "imgs/eisenbahn.jpg",
  },
  {
    id: "brahma",
    name: "Brahma 600ml",
    price: 9.99,
    category: "Cervejas",
    image: "imgs/brahma.jpg",
  },
  {
    id: "devassa",
    name: "Devassa 600ml",
    price: 9.99,
    category: "Cervejas",
    image: "imgs/devassa.webp",
  },
  {
    id: "longneck",
    name: "Long Neck (Heineken, Corona etc.)",
    price: 9.99,
    category: "Cervejas",
    image: "imgs/heinekenlong.jpg",
  },
];
